### ISSUE TITLE
Monodevelop Add NuGet packages

### ISSUE THREAD

**Issue by RossLote** [marshallward/TiledSharp#57]
When I try to install this package I get the following error:

Could not install package 'TiledSharp 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

How do I solve this? I'm relatively new to C# and Nuget.

I have Monodevelop installed on Ubuntu

**Comment by marshallward** [comment]
Sorry about that, the most recent update only provided a 4.5 runtime due to some changes to how the nuget is configured.  Do you know which .NET version you are using?

**Comment by RossLote** [comment]
2.1.202

**Comment by marshallward** [comment]
I don't think this is a NuGet problem, as I was seeing similar errors myself today.

Seems that there have been many changes to how .NET libs are built, and it's overall gotten very confusing for Linux users, since some targets now specifically only target Windows, and Mono seems to honor that more strictly.

But this build process works for me
```
dotnet restore
msbuild
.... (build your code)
mono path/to/exe
```

**Comment by marshallward** [comment]
Closing this for now, but please reopen if you have new information.
